/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import Model.*;
import controller.Data;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.ButtonGroup;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import javax.swing.border.Border;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;
import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.SwingWrapper;
import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.XYChart;

/**
 *
 * @author Alumno
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    private Data d;
    private List<JPanel> lista_candidatos;
    private List<Candidato> lista;
    private List<String> listaId;
    private String valor;
    private ButtonGroup grupo;
    private String rut;
    private List<Resultado> result;
    private SwingWrapper<CategoryChart> sw;

    public App() {
        initComponents();
        d = new Data();
        listaId = new ArrayList<>();
        lista_candidatos = new ArrayList<>();
        lista = new ArrayList<>();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jframe_menu_usuario = new javax.swing.JFrame();
        panel_menu_usuario = new javax.swing.JPanel();
        btn_menu_usuario_listar = new javax.swing.JButton();
        btn_menu_usuario_votar = new javax.swing.JButton();
        btn_menu_usuario_Estadisticas = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        jframe_listar_candidatos = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_volver_lista = new javax.swing.JButton();
        jframe_votar = new javax.swing.JFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        panel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_votar = new javax.swing.JButton();
        jframe_menu_admin = new javax.swing.JFrame();
        panel_menu_admin = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jframe_estadisticas = new javax.swing.JFrame();
        panel_inicio = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_inicio_rut = new javax.swing.JTextField();
        btn_inicio_ingreso = new javax.swing.JButton();

        jframe_menu_usuario.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jframe_menu_usuario.setMinimumSize(new java.awt.Dimension(570, 525));

        panel_menu_usuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menú", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N
        panel_menu_usuario.setMinimumSize(new java.awt.Dimension(550, 620));
        panel_menu_usuario.setPreferredSize(new java.awt.Dimension(550, 1000));

        btn_menu_usuario_listar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_menu_usuario_listar.setText("Consultar lista de candidatos");
        btn_menu_usuario_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_usuario_listarActionPerformed(evt);
            }
        });

        btn_menu_usuario_votar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_menu_usuario_votar.setText("Votar");
        btn_menu_usuario_votar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_usuario_votarActionPerformed(evt);
            }
        });

        btn_menu_usuario_Estadisticas.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_menu_usuario_Estadisticas.setText("Estadísticas");
        btn_menu_usuario_Estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_usuario_EstadisticasActionPerformed(evt);
            }
        });

        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_menu_usuarioLayout = new javax.swing.GroupLayout(panel_menu_usuario);
        panel_menu_usuario.setLayout(panel_menu_usuarioLayout);
        panel_menu_usuarioLayout.setHorizontalGroup(
            panel_menu_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menu_usuarioLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addGroup(panel_menu_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu_usuarioLayout.createSequentialGroup()
                        .addGroup(panel_menu_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_menu_usuario_Estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_menu_usuario_votar, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_menu_usuario_listar))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_menu_usuarioLayout.createSequentialGroup()
                        .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );
        panel_menu_usuarioLayout.setVerticalGroup(
            panel_menu_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_menu_usuarioLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btn_menu_usuario_listar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btn_menu_usuario_Estadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btn_menu_usuario_votar, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );

        javax.swing.GroupLayout jframe_menu_usuarioLayout = new javax.swing.GroupLayout(jframe_menu_usuario.getContentPane());
        jframe_menu_usuario.getContentPane().setLayout(jframe_menu_usuarioLayout);
        jframe_menu_usuarioLayout.setHorizontalGroup(
            jframe_menu_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_menu_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_menu_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jframe_menu_usuarioLayout.setVerticalGroup(
            jframe_menu_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_menu_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_menu_usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jframe_listar_candidatos.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jframe_listar_candidatos.setMinimumSize(new java.awt.Dimension(458, 473));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel.setLayout(new java.awt.GridLayout(0, 1, 20, 10));
        jScrollPane1.setViewportView(panel);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Candidatos a la presidencia: ");

        btn_volver_lista.setText("Volver");
        btn_volver_lista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volver_listaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jframe_listar_candidatosLayout = new javax.swing.GroupLayout(jframe_listar_candidatos.getContentPane());
        jframe_listar_candidatos.getContentPane().setLayout(jframe_listar_candidatosLayout);
        jframe_listar_candidatosLayout.setHorizontalGroup(
            jframe_listar_candidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_listar_candidatosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jframe_listar_candidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jframe_listar_candidatosLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframe_listar_candidatosLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_volver_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jframe_listar_candidatosLayout.setVerticalGroup(
            jframe_listar_candidatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_listar_candidatosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btn_volver_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jframe_votar.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jframe_votar.setMinimumSize(new java.awt.Dimension(538, 468));

        panel1.setLayout(new java.awt.GridLayout(0, 1, 20, 20));
        jScrollPane2.setViewportView(panel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Votación:");

        btn_votar.setText("Realizar Votación");
        btn_votar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_votarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addComponent(btn_votar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_votar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jframe_votarLayout = new javax.swing.GroupLayout(jframe_votar.getContentPane());
        jframe_votar.getContentPane().setLayout(jframe_votarLayout);
        jframe_votarLayout.setHorizontalGroup(
            jframe_votarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_votarLayout.createSequentialGroup()
                .addGroup(jframe_votarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jframe_votarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jframe_votarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jframe_votarLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jframe_votarLayout.setVerticalGroup(
            jframe_votarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jframe_votarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jframe_menu_admin.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_menu_admin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Admin", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 2, 18))); // NOI18N

        javax.swing.GroupLayout panel_menu_adminLayout = new javax.swing.GroupLayout(panel_menu_admin);
        panel_menu_admin.setLayout(panel_menu_adminLayout);
        panel_menu_adminLayout.setHorizontalGroup(
            panel_menu_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        panel_menu_adminLayout.setVerticalGroup(
            panel_menu_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 410, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jframe_menu_adminLayout = new javax.swing.GroupLayout(jframe_menu_admin.getContentPane());
        jframe_menu_admin.getContentPane().setLayout(jframe_menu_adminLayout);
        jframe_menu_adminLayout.setHorizontalGroup(
            jframe_menu_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_menu_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_menu_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jframe_menu_adminLayout.setVerticalGroup(
            jframe_menu_adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jframe_menu_adminLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_menu_admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jframe_estadisticasLayout = new javax.swing.GroupLayout(jframe_estadisticas.getContentPane());
        jframe_estadisticas.getContentPane().setLayout(jframe_estadisticasLayout);
        jframe_estadisticasLayout.setHorizontalGroup(
            jframe_estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 608, Short.MAX_VALUE)
        );
        jframe_estadisticasLayout.setVerticalGroup(
            jframe_estadisticasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_inicio.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Sistema Super Seguro de Votacion c:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Ingrese su rut: ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("(Ej: 12345678-9)");

        txt_inicio_rut.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_inicio_rut.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btn_inicio_ingreso.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btn_inicio_ingreso.setText("Ingresar");
        btn_inicio_ingreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inicio_ingresoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_inicioLayout = new javax.swing.GroupLayout(panel_inicio);
        panel_inicio.setLayout(panel_inicioLayout);
        panel_inicioLayout.setHorizontalGroup(
            panel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inicioLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(panel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inicioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(52, 52, 52))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_inicioLayout.createSequentialGroup()
                        .addComponent(btn_inicio_ingreso)
                        .addGap(211, 211, 211))))
            .addGroup(panel_inicioLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(panel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(txt_inicio_rut, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panel_inicioLayout.setVerticalGroup(
            panel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_inicioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addGroup(panel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_inicio_rut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_inicioLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(92, 92, 92)
                .addComponent(btn_inicio_ingreso)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menu_usuario_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_usuario_listarActionPerformed
//        Pais p = new Pais();
//        p.setNombre("chile");
//        
//        d.agregarPais(p);
        jframe_menu_usuario.setVisible(false);
        jframe_listar_candidatos.setVisible(true);

        lista = d.lista_candidatos();

        for (Candidato c : lista) {

            JPanel jp = new JPanel();
            JLabel lbl1 = new JLabel(c.getRut());
            JLabel lbl2 = new JLabel(c.getNombre());
            JLabel lbl3 = new JLabel(c.getNombre_partido());

            Border etched = BorderFactory.createEtchedBorder();
            jp.setLayout(new GridLayout(0, 1, 5, 5));
            jp.setBorder(etched);
            jp.add(lbl1);
            jp.add(lbl2);
            jp.add(lbl3);

            panel.add(jp);
            panel.updateUI();

        }


    }//GEN-LAST:event_btn_menu_usuario_listarActionPerformed

    private void btn_inicio_ingresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inicio_ingresoActionPerformed

        rut = txt_inicio_rut.getText();
        //Persona p = d.getPersona(rut);
//        System.out.println("Persona: " + p.getNombre());
        if (rut.equals("") || !rut.equals(d.getPersona(rut).getRut())) {
            JOptionPane.showMessageDialog(this, "Rut no vali3", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else if (rut.equals(d.getPersona(rut).getRut())) {
            this.setVisible(false);
            jframe_menu_usuario.setVisible(true);
        }


    }//GEN-LAST:event_btn_inicio_ingresoActionPerformed

    private void btn_menu_usuario_votarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_usuario_votarActionPerformed
        jframe_menu_usuario.setVisible(false);
        jframe_votar.setVisible(true);

        lista = d.lista_candidatos();

        grupo = new ButtonGroup();
        Border etched = BorderFactory.createEtchedBorder();

        for (Candidato c : lista) {

            JRadioButton jb = new JRadioButton();

            jb.setName(String.valueOf(c.getId()));

            String lbl1 = c.getNombre();
            String lbl2 = c.getNombre_partido();

            jb.setText("<html>" + lbl1 + "<br>" + lbl2 + "</html>");
            jb.setBorder(etched);

            grupo.add(jb);
            panel1.add(jb);

            panel.updateUI();

            listaId.add(String.valueOf(c.getId()));

        }
    }//GEN-LAST:event_btn_menu_usuario_votarActionPerformed

    private void btn_votarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_votarActionPerformed

        System.out.println("id Candidato: " + getSelectedButtonText(grupo));
        System.out.println("id persona: " + d.getPersona(rut).getId());

        if ( getSelectedButtonText(grupo) == null) {
            JOptionPane.showConfirmDialog(this, "Usted ya ha votado", "Atención", JOptionPane.CLOSED_OPTION);
            jframe_votar.setVisible(false);
            jframe_menu_usuario.setVisible(true);
        } else {

            d.votar(d.getPersona(rut), getSelectedButtonText(grupo));

            JOptionPane.showConfirmDialog(this, "Usted sera redirigido", "Gracias por Votar", JOptionPane.CLOSED_OPTION);
            jframe_votar.setVisible(false);
            this.setVisible(true);

        }

//        System.out.println("id partido: "+getSelectedButtonText(grupo));
//        System.out.println("Id Partido: "+d.getPartidoId(getSelectedButtonText(grupo)));
    }//GEN-LAST:event_btn_votarActionPerformed

    private void btn_menu_usuario_EstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_usuario_EstadisticasActionPerformed
        jframe_menu_usuario.setVisible(true);

        result = d.resultados();
        List<String> nombres = new ArrayList<>();
        List<Integer> votos = new ArrayList<Integer>();

        final CategoryChart chart = new CategoryChartBuilder().width(800).height(500).xAxisTitle("Candidatos").yAxisTitle("Cant. Votos").title("Votaciones").build();

        for (Resultado r : result) {

            Candidato c = d.getCandidatoId(r.getCandidato());
            nombres.add(c.getNombre());
            votos.add(r.getCantidad());
            System.out.println(nombres);
            System.out.println(votos);

        }
        chart.addSeries("Votaciones", nombres, votos);
//        chart.addSeries("Votaciones", new double[]{2,3,4},new double[]{5,6,7});

        sw = new SwingWrapper<>(chart);

        new Thread(new Runnable() {
            @Override
            public void run() {
                sw.displayChart().setDefaultCloseOperation(WindowConstants.HIDE_ON_CLOSE);

            }
        }).start();
//        javax.swing.SwingUtilities.invokeLater(new Runnable() {
//
//            @Override
//            public void run() {
//
//                JPanel chartPanel = new XChartPanel<>(chart);
//                chartPanel.setVisible(true);
//
//                JLabel label = new JLabel("Estadísticas de votaciones", SwingConstants.CENTER);
//
//                jframe_estadisticas.add(chartPanel);
//
//                jframe_estadisticas.validate();
//                jframe_estadisticas.pack();
//                jframe_estadisticas.setVisible(true);
//
//                jframe_estadisticas.setBounds(20, 20, 800, 600);
//            }
//        });


    }//GEN-LAST:event_btn_menu_usuario_EstadisticasActionPerformed

    private void btn_volver_listaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volver_listaActionPerformed
        jframe_listar_candidatos.setVisible(false);
        jframe_menu_usuario.setVisible(true);
    }//GEN-LAST:event_btn_volver_listaActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        jframe_menu_usuario.setVisible(false);
        this.setVisible(true);
        txt_inicio_rut.setText(null);
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_inicio_ingreso;
    private javax.swing.JButton btn_menu_usuario_Estadisticas;
    private javax.swing.JButton btn_menu_usuario_listar;
    private javax.swing.JButton btn_menu_usuario_votar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_volver_lista;
    private javax.swing.JButton btn_votar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JFrame jframe_estadisticas;
    private javax.swing.JFrame jframe_listar_candidatos;
    private javax.swing.JFrame jframe_menu_admin;
    private javax.swing.JFrame jframe_menu_usuario;
    private javax.swing.JFrame jframe_votar;
    private javax.swing.JPanel panel;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel_inicio;
    private javax.swing.JPanel panel_menu_admin;
    private javax.swing.JPanel panel_menu_usuario;
    private javax.swing.JTextField txt_inicio_rut;
    // End of variables declaration//GEN-END:variables

    public String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getName();
            }
        }
        return null;
    }

//    private static String getHash(String txt, String hashType) {
//        try {
//            java.security.MessageDigest md = java.security.MessageDigest.getInstance(hashType);
//            byte[] array = md.digest(txt.getBytes());
//            StringBuffer sb = new StringBuffer();
//            for (int i = 0; i < array.length; ++i) {
//                sb.append(Integer.toHexString((array[i] & 0xFF) | 0x100).substring(1, 3));
//            }
//            return sb.toString();
//        } catch (java.security.NoSuchAlgorithmException e) {
//            System.out.println(e.getMessage());
//        }
//        return null;
//    }
//
//    private String md5(String txt) {
//        return getHash(txt, "MD5");
//    }
}
